const manaMap = {
  '1': '/mana/1.png',
  '2': '/mana/2.png',
  '2b': '/mana/2b.png',
  '2u': '/mana/2u.png',
  '2bu': '/mana/2bu.png',
  '2g': '/mana/2g.png',
  '2r': '/mana/2r.png',
  '2w': '/mana/2w.png',
  '3': '/mana/3.png',
  '4': '/mana/4.png',
  '5': '/mana/5.png',
  '6': '/mana/6.png',
  '7': '/mana/7.png',
  '8': '/mana/8.png',
  '9': '/mana/9.png',
  'b': '/mana/b.png',
  'bg': '/mana/bg.png',
  'br': '/mana/br.png',
  'u': '/mana/u.png',
  'bub': '/mana/bub.png',
  'bur': '/mana/bur.png',
  'cb': '/mana/cb.png',
  'cbu': '/mana/cbu.png',
  'cg': '/mana/cg.png',
  'c': '/mana/c.png',
  'cr': '/mana/cr.png',
  'cw': '/mana/cw.png',
  'g': '/mana/g.png',
  'gbu': '/mana/gbu.png',
  'gw': '/mana/gw.png',
  'pgbu': '/mana/pgbu.png',
  'pgw': '/mana/pgw.png',
  'prg': '/mana/prg.png',
  'prw': '/mana/prw.png',
  'r': '/mana/r.png',
  'rg': '/mana/rg.png',
  'rw': '/mana/rw.png',
  'tap': '/mana/tap.png',
  'w': '/mana/w.png',
  'wb': '/mana/wb.png',
  'wbu': '/mana/wbu.png',
  'x': '/mana/x.png',
};

// ESM export for Vite/Konva consumers
export default manaMap;
